// Import Plugins
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;

export default function createPDF(doc) {
  var docDefinition = {
    pageSize: "A4",
    // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
    pageMargins: [40, 60, 160, 60],

    content: [
      {
        stack: [
          `SRS Generator`,
          {
            text: `A generator of System Requirement Specification to avoid the lack of vision and structure at the beginning of new projects.`,
            style: "subheader",
          },
        ],
        style: "heading1",
      },
      {
        text: [
          "Document generated by ",
          { text: "SRSGEN", link: "http://srsgen.com", color: "blue" },
        ],
        style: ["quote", "small"],
        pageBreak: "after",
      },
      {
        stack: [
          `Goals and Description`,
          {
            text: `A generator of System Requirement Specification to avoid the lack of vision and structure at the beginning of new projects.`,
            style: "subheader",
          },
        ],
        style: "heading2",
      },
      {
        stack: [
          `Goals and Description`,
          {
            text: `A generator of System Requirement Specification to avoid the lack of vision and structure at the beginning of new projects.`,
            style: "subheader",
          },
        ],
        style: "heading2",
      },
      {
        stack: [
          `Goals and Description`,
          {
            text: `A generator of System Requirement Specification to avoid the lack of vision and structure at the beginning of new projects.`,
            style: "subheader",
          },
        ],
        style: "heading2",
      },
      {
        stack: [
          `Goals and Description`,
          {
            text: `A generator of System Requirement Specification to avoid the lack of vision and structure at the beginning of new projects.`,
            style: "subheader",
          },
        ],
        style: "heading2",
      },
      {
        stack: [
          `Goals and Description`,
          {
            text: `A generator of System Requirement Specification to avoid the lack of vision and structure at the beginning of new projects.`,
            style: "subheader",
          },
        ],
        style: "heading2",
      },
    ],
    styles: {
      heading1: {
        fontSize: 32,
        bold: true,
        margin: [0, 130, 0, 10],
      },
      subheader: {
        fontSize: 14,
        bold: false,
        margin: [0, 5, 0, 0],
      },
      superMargin: {
        margin: [0, 0, 40, 0],
        fontSize: 15,
      },
      heading2: {
        fontSize: 18,
        bold: true,
        margin: [0, 0, 0, 30],
      },
      quote: {
        italics: true,
        margin: [0, 30, 0, 0],
      },
      small: {
        fontSize: 8,
      },
    },
  };

  pdfMake.createPdf(docDefinition).download();
}
